export const acquisitionStyles = [
  'Sync',
  'PostDicom Direct',
  'Manual/Webform',
  'Scheduled',
  'Manual Export w/ Sync',
]

export const exportWords = [
  'ExportDICOMs',
  'DicomsExport',
  'ExportFilesDicoms',
  'ExportImagesDicoms',
  'DICOMsExportFiles',
  'ExportDicomFiles',
  'ExportDataDicoms',
  'DicomsExportData',
  'DicomsExportFilesData',
  'ExportDICOMImages',
  'DICOMsExportImages',
  'ExportDicoms',
  'ExportData',
  'ExportDICOMData',
  'DicomsExportImages',
  'DicomsExportDataFiles',
  'ExportDataFiles',
  'ExportImages',
  'ExportDicomsData',
  'ExportDICOMFiles',
];

export const managemenetSoftwares = [
  'Slack',
  'Trello',
  'Asana',
  'Jira',
  'Microsoft Teams',
  'Monday.com',
  'Basecamp',
  'Notion',
  'Airtable',
  'ClickUp',
  'Todoist',
  'Wrike',
  'Evernote',
  'Google Workspace',
  'Confluence',
  'Zoom',
  'GitHub',
  'GitLab',
  'Salesforce',
  'Zendesk',
]

export const imageViewingSoftwares = [
  'OsiriX',
  'Horos',
  '3D Slicer',
  'Aeskulap',
  'RadiAnt DICOM Viewer',
  'Weasis',
  'MicroDicom',
  'Sante DICOM Viewer Free',
  'DicomWorks',
  'MedDream DICOM Viewer',
  'AMIDE',
  'ClearCanvas Workstation',
  'Mango',
  'Conquest DICOM Server and Client',
  'Orthanc',
  'itk-SNAP',
  'MITO',
  'Ginkgo CADx',
  'K-PACS',
  'InVesalius',
]

export const cbctModels = [
  'Planmeca ProMax 3D',
  'Carestream CS 9300',
  'Vatech PaX-i3D Green',
  'Morita 3D Accuitomo',
  'Sirona Orthophos XG 3D',
  'Gendex CB-500',
  'NewTom 5G',
  'Kavo OP 3D',
  'PreXion3D Excelsior',
  'J. Morita Veraview IC5 HD',
  'Genoray Zenith CBCT',
  'i-CAT FLX V-Series',
  'Cefla NewTom VG3',
  'Villa Sistemi Medicali X-Mind Unity',
  'LargeV Ceph3D',
  'MyRay Hyperion X5',
  'Owandy I-Max Touch 3D',
  'Asahi Roentgen Profex HD',
  'PointNix Accuitomo F170',
  'Gendex GXDP-700',
]

export const dicomModalities = [
  'XA - X-Ray Angiography',
  'CT - Computed Tomography',
  'MR - Magnetic Resonance Imaging',
  'US - Ultrasound',
  'PET - Positron Emission Tomography',
  'NM - Nuclear Medicine',
  'MG - Mammography',
  'RF - Radiographic Fluoroscopy',
  'CR - Computed Radiography',
  'DR - Digital Radiography',
  'DX - Digital Mammography',
  'CT - Computed Tomography',
  'MR - Magnetic Resonance',
  'NM - Nuclear Medicine',
  'US - Ultrasound',
  'XA - X-Ray Angiography',
  'XRF - X-Ray Fluoroscopy',
  'DX - Digital Mammography',
  'MR - Magnetic Resonance Imaging',
  'CR - Computed Radiography',
  'RT - Radiotherapy',
  'DSA - Digital Subtraction Angiography',
  'BD - Bone Densitometry',
  'IR - Interventional Radiology',
  'XRF - X-Ray Fluoroscopy',
  'XA - X-Ray Angiography',
  'DX - Digital Mammography',
  'MR - Magnetic Resonance',
  'XRF - X-Ray Fluoroscopy',
  'SC - Secondary Capture',
  'VL - Visible Light',
  'OP - Ophthalmic Photography',
  'RG - Radiographic Imaging',
  'RTDOSE - Radiotherapy Dose',
  'RTPLAN - Radiotherapy Plan',
  'RTSTRUCT - Radiotherapy Structure Set',
  'PR - Presentation State',
  'AR - Autorefraction',
  'IO - Intra-oral Radiography',
  'IVUS - Intravascular Ultrasound',
]