export function getRandomNumberFromRange(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

export const countryCodeFormats = [
  {isoTwo: "AF", code: "93", name: "Afghanistan", format: "## ### ####"},
  {isoTwo: "AL", code: "355", name: "Albania", format: "## ### ####"},
  {isoTwo: "DZ", code: "213", name: "Algeria", format: "## ### ####"},
  {isoTwo: "AS", code: "1-684", name: "American Samoa", format: "###-####"},
  {isoTwo: "AD", code: "376", name: "Andorra", format: "### ###"},
  {isoTwo: "AO", code: "244", name: "Angola", format: "### ### ###"},
  {isoTwo: "AI", code: "1-264", name: "Anguilla", format: "### ####"},
  {isoTwo: "AQ", code: "672", name: "Antarctica", format: "### ### ####"},
  {isoTwo: "AG", code: "1-268", name: "Antigua and Barbuda", format: "###-####"},
  {isoTwo: "AR", code: "54", name: "Argentina", format: "## #### ####"},
  {isoTwo: "AM", code: "374", name: "Armenia", format: "## #######"},
  {isoTwo: "AW", code: "297", name: "Aruba", format: "### ####"},
  {isoTwo: "AU", code: "61", name: "Australia", format: "# #### ####"},
  {isoTwo: "AT", code: "43", name: "Austria", format: "### #######"},
  {isoTwo: "AZ", code: "994", name: "Azerbaijan", format: "## ### ## ##"},
  {isoTwo: "BS", code: "1-242", name: "Bahamas", format: "###-####"},
  {isoTwo: "BH", code: "973", name: "Bahrain", format: "#### ####"},
  {isoTwo: "BD", code: "880", name: "Bangladesh", format: "#####-#####"},
  {isoTwo: "BB", code: "1-246", name: "Barbados", format: "###-####"},
  {isoTwo: "BY", code: "375", name: "Belarus", format: "## ### ## ##"},
  {isoTwo: "BE", code: "32", name: "Belgium", format: "### ## ## ##"},
  {isoTwo: "BZ", code: "501", name: "Belize", format: "###-####"},
  {isoTwo: "BJ", code: "229", name: "Benin", format: "## ## ## ##"},
  {isoTwo: "BM", code: "1-441", name: "Bermuda", format: "###-####"},
  {isoTwo: "BT", code: "975", name: "Bhutan", format: "## ## ## ##"},
  {isoTwo: "BO", code: "591", name: "Bolivia", format: "# #### ####"},
  {isoTwo: "BA", code: "387", name: "Bosnia and Herzegovina", format: "## ### ####"},
  {isoTwo: "BW", code: "267", name: "Botswana", format: "## ### ####"},
  {isoTwo: "BR", code: "55", name: "Brazil", format: "## ####-####"},
  {isoTwo: "IO", code: "246", name: "British Indian Ocean Territory", format: "### ### ####"},
  {isoTwo: "VG", code: "1-284", name: "British Virgin Islands", format: "###-####"},
  {isoTwo: "BN", code: "673", name: "Brunei", format: "### ####"},
  {isoTwo: "BG", code: "359", name: "Bulgaria", format: "### ### ###"},
  {isoTwo: "BF", code: "226", name: "Burkina Faso", format: "## ## ## ##"},
  {isoTwo: "BI", code: "257", name: "Burundi", format: "## ## ## ##"},
  {isoTwo: "KH", code: "855", name: "Cambodia", format: "## ### ####"},
  {isoTwo: "CM", code: "237", name: "Cameroon", format: "#### #### ##"},
  {isoTwo: "CA", code: "1", name: "Canada", format: "###-###-####"},
  {isoTwo: "CV", code: "238", name: "Cape Verde", format: "### ## ##"},
  {isoTwo: "KY", code: "1-345", name: "Cayman Islands", format: "###-####"},
  {isoTwo: "CF", code: "236", name: "Central African Republic", format: "## ## ## ##"},
  {isoTwo: "TD", code: "235", name: "Chad", format: "## ## ## ##"},
  {isoTwo: "CL", code: "56", name: "Chile", format: "# #### ####"},
  {isoTwo: "CN", code: "86", name: "China", format: "## #### ####"},
  {isoTwo: "CX", code: "61", name: "Christmas Island", format: "### ####"},
  {isoTwo: "CC", code: "61", name: "Cocos Islands", format: "### ####"},
  {isoTwo: "CO", code: "57", name: "Colombia", format: "### ### ####"},
  {isoTwo: "KM", code: "269", name: "Comoros", format: "### ## ##"},
  {isoTwo: "CK", code: "682", name: "Cook Islands", format: "## ###"},
  {isoTwo: "CR", code: "506", name: "Costa Rica", format: "#### ####"},
  {isoTwo: "HR", code: "385", name: "Croatia", format: "## ### ####"},
  {isoTwo: "CU", code: "53", name: "Cuba", format: "# #### ####"},
  {isoTwo: "CW", code: "599", name: "Curacao", format: "### ####"},
  {isoTwo: "CY", code: "357", name: "Cyprus", format: "## ### ###"},
  {isoTwo: "CZ", code: "420", name: "Czech Republic", format: "### ### ###"},
  {isoTwo: "CD", code: "243", name: "Democratic Republic of the Congo", format: "### ### ###"},
  {isoTwo: "DK", code: "45", name: "Denmark", format: "## ## ## ##"},
  {isoTwo: "DJ", code: "253", name: "Djibouti", format: "## ## ## ##"},
  {isoTwo: "DM", code: "1-767", name: "Dominica", format: "###-####"},
  {isoTwo: "DO", code: "1-809, 1-829, 1-849", name: "Dominican Republic", format: "###-####"},
  {isoTwo: "TL", code: "670", name: "East Timor", format: "## ### ####"},
  {isoTwo: "EC", code: "593", name: "Ecuador", format: "## ### ####"},
  {isoTwo: "EG", code: "20", name: "Egypt", format: "## ### ####"},
  {isoTwo: "SV", code: "503", name: "El Salvador", format: "#### ####"},
  {isoTwo: "GQ", code: "240", name: "Equatorial Guinea", format: "## ### ####"},
  {isoTwo: "ER", code: "291", name: "Eritrea", format: "## ### ###"},
  {isoTwo: "EE", code: "372", name: "Estonia", format: "### ####"},
  {isoTwo: "ET", code: "251", name: "Ethiopia", format: "## ### ####"},
  {isoTwo: "FK", code: "500", name: "Falkland Islands", format: "#####"},
  {isoTwo: "FO", code: "298", name: "Faroe Islands", format: "### ###"},
  {isoTwo: "FJ", code: "679", name: "Fiji", format: "## #####"},
  {isoTwo: "FI", code: "358", name: "Finland", format: "## ### ## ##"},
  {isoTwo: "FR", code: "33", name: "France", format: "# ## ## ## ##"},
  {isoTwo: "PF", code: "689", name: "French Polynesia", format: "## ## ## ##"},
  {isoTwo: "GA", code: "241", name: "Gabon", format: "## ## ## ##"},
  {isoTwo: "GM", code: "220", name: "Gambia", format: "## ## ####"},
  {isoTwo: "GE", code: "995", name: "Georgia", format: "### ## ## ##"},
  {isoTwo: "DE", code: "49", name: "Germany", format: "### ### ####"},
  {isoTwo: "GH", code: "233", name: "Ghana", format: "### ### ###"},
  {isoTwo: "GI", code: "350", name: "Gibraltar", format: "### ####"},
  {isoTwo: "GR", code: "30", name: "Greece", format: "### ### ####"},
  {isoTwo: "GL", code: "299", name: "Greenland", format: "## ## ##"},
  {isoTwo: "GD", code: "1-473", name: "Grenada", format: "###-####"},
  {isoTwo: "GU", code: "1-671", name: "Guam", format: "###-####"},
  {isoTwo: "GT", code: "502", name: "Guatemala", format: "#### ####"},
  {isoTwo: "GG", code: "44-1481", name: "Guernsey", format: "#### ####"},
  {isoTwo: "GN", code: "224", name: "Guinea", format: "## ### ####"},
  {isoTwo: "GW", code: "245", name: "Guinea-Bissau", format: "## ######"},
  {isoTwo: "GY", code: "592", name: "Guyana", format: "### ####"},
  {isoTwo: "HT", code: "509", name: "Haiti", format: "## ## ####"},
  {isoTwo: "HN", code: "504", name: "Honduras", format: "####-####"},
  {isoTwo: "HK", code: "852", name: "Hong Kong", format: "#### ####"},
  {isoTwo: "HU", code: "36", name: "Hungary", format: "## ### ####"},
  {isoTwo: "IS", code: "354", name: "Iceland", format: "### ####"},
  {isoTwo: "IN", code: "91", name: "India", format: "#####-#####"},
  {isoTwo: "ID", code: "62", name: "Indonesia", format: "## #### ####"},
  {isoTwo: "IR", code: "98", name: "Iran", format: "### ### ####"},
  {isoTwo: "IQ", code: "964", name: "Iraq", format: "### ### ####"},
  {isoTwo: "IE", code: "353", name: "Ireland", format: "## ### ####"},
  {isoTwo: "IM", code: "44-1624", name: "Isle of Man", format: "#### ######"},
  {isoTwo: "IL", code: "972", name: "Israel", format: "#-###-####"},
  {isoTwo: "IT", code: "39", name: "Italy", format: "### #######"},
  {isoTwo: "CI", code: "225", name: "Ivory Coast", format: "## ## ## ##"},
  {isoTwo: "JM", code: "1-876", name: "Jamaica", format: "###-####"},
  {isoTwo: "JP", code: "81", name: "Japan", format: "## #### ####"},
  {isoTwo: "JE", code: "44-1534", name: "Jersey", format: "#### ####"},
  {isoTwo: "JO", code: "962", name: "Jordan", format: "## #### ####"},
  {isoTwo: "KZ", code: "7", name: "Kazakhstan", format: "### ### ## ##"},
  {isoTwo: "KE", code: "254", name: "Kenya", format: "### ### ###"},
  {isoTwo: "KI", code: "686", name: "Kiribati", format: "## ###"},
  {isoTwo: "XK", code: "383", name: "Kosovo", format: "## ### ####"},
  {isoTwo: "KW", code: "965", name: "Kuwait", format: "#### ####"},
  {isoTwo: "KG", code: "996", name: "Kyrgyzstan", format: "### ## ## ##"},
  {isoTwo: "LA", code: "856", name: "Laos", format: "## ## ### ###"},
  {isoTwo: "LV", code: "371", name: "Latvia", format: "## ### ####"},
  {isoTwo: "LB", code: "961", name: "Lebanon", format: "## ### ###"},
  {isoTwo: "LS", code: "266", name: "Lesotho", format: "## ### ####"},
  {isoTwo: "LR", code: "231", name: "Liberia", format: "## ### ####"},
  {isoTwo: "LY", code: "218", name: "Libya", format: "## ### ####"},
  {isoTwo: "LI", code: "423", name: "Liechtenstein", format: "### ### ####"},
  {isoTwo: "LT", code: "370", name: "Lithuania", format: "## ## ### ####"},
  {isoTwo: "LU", code: "352", name: "Luxembourg", format: "### ### ###"},
  {isoTwo: "MO", code: "853", name: "Macau", format: "#### ####"},
  {isoTwo: "MK", code: "389", name: "Macedonia", format: "## ### ####"},
  {isoTwo: "MG", code: "261", name: "Madagascar", format: "## ## ####"},
  {isoTwo: "MW", code: "265", name: "Malawi", format: "### ## ####"},
  {isoTwo: "MY", code: "60", name: "Malaysia", format: "##-### ####"},
  {isoTwo: "MV", code: "960", name: "Maldives", format: "###-####"},
  {isoTwo: "ML", code: "223", name: "Mali", format: "## ## ## ##"},
  {isoTwo: "MT", code: "356", name: "Malta", format: "#### ####"},
  {isoTwo: "MH", code: "692", name: "Marshall Islands", format: "###-####"},
  {isoTwo: "MR", code: "222", name: "Mauritania", format: "## ## ## ##"},
  {isoTwo: "MU", code: "230", name: "Mauritius", format: "### ####"},
  {isoTwo: "YT", code: "262", name: "Mayotte", format: "## ## ## ##"},
  {isoTwo: "MX", code: "52", name: "Mexico", format: "## #### ####"},
  {isoTwo: "FM", code: "691", name: "Micronesia", format: "###-####"},
  {isoTwo: "MD", code: "373", name: "Moldova", format: "### ######"},
  {isoTwo: "MC", code: "377", name: "Monaco", format: "## ### ## ##"},
  {isoTwo: "MN", code: "976", name: "Mongolia", format: "## ## ## ##"},
  {isoTwo: "ME", code: "382", name: "Montenegro", format: "## ### ####"},
  {isoTwo: "MS", code: "1-664", name: "Montserrat", format: "###-####"},
  {isoTwo: "MA", code: "212", name: "Morocco", format: "## #### ####"},
  {isoTwo: "MZ", code: "258", name: "Mozambique", format: "## ### ####"},
  {isoTwo: "MM", code: "95", name: "Myanmar", format: "## ### ####"},
  {isoTwo: "NA", code: "264", name: "Namibia", format: "## ### ####"},
  {isoTwo: "NR", code: "674", name: "Nauru", format: "### ####"},
  {isoTwo: "NP", code: "977", name: "Nepal", format: "## ### ####"},
  {isoTwo: "NL", code: "31", name: "Netherlands", format: "## ### ####"},
  {isoTwo: "AN", code: "599", name: "Netherlands Antilles", format: "### ####"},
  {isoTwo: "NC", code: "687", name: "New Caledonia", format: "## ####"},
  {isoTwo: "NZ", code: "64", name: "New Zealand", format: "### ### ####"},
  {isoTwo: "NI", code: "505", name: "Nicaragua", format: "#### ####"},
  {isoTwo: "NE", code: "227", name: "Niger", format: "## ## ####"},
  {isoTwo: "NG", code: "234", name: "Nigeria", format: "### ### ####"},
  {isoTwo: "NU", code: "683", name: "Niue", format: "### ####"},
  {isoTwo: "KP", code: "850", name: "North Korea", format: "### #### ####"},
  {isoTwo: "MP", code: "1-670", name: "Northern Mariana Islands", format: "###-####"},
  {isoTwo: "NO", code: "47", name: "Norway", format: "## ## ## ##"},
  {isoTwo: "OM", code: "968", name: "Oman", format: "## ### ###"},
  {isoTwo: "PK", code: "92", name: "Pakistan", format: "###-#######"},
  {isoTwo: "PW", code: "680", name: "Palau", format: "###-####"},
  {isoTwo: "PS", code: "970", name: "Palestine", format: "## ### ####"},
  {isoTwo: "PA", code: "507", name: "Panama", format: "### ####"},
  {isoTwo: "PG", code: "675", name: "Papua New Guinea", format: "### ####"},
  {isoTwo: "PY", code: "595", name: "Paraguay", format: "### #######"},
  {isoTwo: "PE", code: "51", name: "Peru", format: "## ### ####"},
  {isoTwo: "PH", code: "63", name: "Philippines", format: "### #######"},
  {isoTwo: "PN", code: "64", name: "Pitcairn", format: "### ####"},
  {isoTwo: "PL", code: "48", name: "Poland", format: "### ### ###"},
  {isoTwo: "PT", code: "351", name: "Portugal", format: "### ### ###"},
  {isoTwo: "PR", code: "1-787, 1-939", name: "Puerto Rico", format: "###-####"},
  {isoTwo: "QA", code: "974", name: "Qatar", format: "#### ####"},
  {isoTwo: "CG", code: "242", name: "Republic of the Congo", format: "## ### ####"},
  {isoTwo: "RE", code: "262", name: "Reunion", format: "## ## ## ##"},
  {isoTwo: "RO", code: "40", name: "Romania", format: "## ### ####"},
  {isoTwo: "RU", code: "7", name: "Russia", format: "### ### ## ##"},
  {isoTwo: "RW", code: "250", name: "Rwanda", format: "### ### ###"},
  {isoTwo: "BL", code: "590", name: "Saint Barthelemy", format: "## ## ## ##"},
  {isoTwo: "SH", code: "290", name: "Saint Helena", format: "### ####"},
  {isoTwo: "KN", code: "1-869", name: "Saint Kitts and Nevis", format: "###-####"},
  {isoTwo: "LC", code: "1-758", name: "Saint Lucia", format: "###-####"},
  {isoTwo: "MF", code: "590", name: "Saint Martin", format: "### ####"},
  {isoTwo: "PM", code: "508", name: "Saint Pierre and Miquelon", format: "## ## ## ##"},
  {isoTwo: "VC", code: "1-784", name: "Saint Vincent and the Grenadines", format: "###-####"},
  {isoTwo: "WS", code: "685", name: "Samoa", format: "## ####"},
  {isoTwo: "SM", code: "378", name: "San Marino", format: "## ## ## ##"},
  {isoTwo: "ST", code: "239", name: "Sao Tome and Principe", format: "## ####"},
  {isoTwo: "SA", code: "966", name: "Saudi Arabia", format: "## #### ####"},
  {isoTwo: "SN", code: "221", name: "Senegal", format: "## ### ## ##"},
  {isoTwo: "RS", code: "381", name: "Serbia", format: "## ### ####"},
  {isoTwo: "SC", code: "248", name: "Seychelles", format: "### ####"},
  {isoTwo: "SL", code: "232", name: "Sierra Leone", format: "## #### ####"},
  {isoTwo: "SG", code: "65", name: "Singapore", format: "#### ####"},
  {isoTwo: "SX", code: "1-721", name: "Sint Maarten", format: "### ####"},
  {isoTwo: "SK", code: "421", name: "Slovakia", format: "### ### ###"},
  {isoTwo: "SI", code: "386", name: "Slovenia", format: "## ### ## ##"},
  {isoTwo: "SB", code: "677", name: "Solomon Islands", format: "### ####"},
  {isoTwo: "SO", code: "252", name: "Somalia", format: "## ### ###"},
  {isoTwo: "ZA", code: "27", name: "South Africa", format: "## ### ####"},
  {isoTwo: "KR", code: "82", name: "South Korea", format: "##-###-####"},
  {isoTwo: "SS", code: "211", name: "South Sudan", format: "## ### ####"},
  {isoTwo: "ES", code: "34", name: "Spain", format: "### ### ###"},
  {isoTwo: "LK", code: "94", name: "Sri Lanka", format: "## ### ####"},
  {isoTwo: "SD", code: "249", name: "Sudan", format: "## ### ####"},
  {isoTwo: "SR", code: "597", name: "Suriname", format: "### ####"},
  {isoTwo: "SJ", code: "47", name: "Svalbard and Jan Mayen", format: "## ## ## ##"},
  {isoTwo: "SZ", code: "268", name: "Swaziland", format: "## ## ## ##"},
  {isoTwo: "SE", code: "46", name: "Sweden", format: "##-### ## ##"},
  {isoTwo: "CH", code: "41", name: "Switzerland", format: "## ### ## ##"},
  {isoTwo: "SY", code: "963", name: "Syria", format: "## ### ####"},
  {isoTwo: "TW", code: "886", name: "Taiwan", format: "### #### ####"},
  {isoTwo: "TJ", code: "992", name: "Tajikistan", format: "### ## ####"},
  {isoTwo: "TZ", code: "255", name: "Tanzania", format: "## ### ####"},
  {isoTwo: "TH", code: "66", name: "Thailand", format: "## ### ####"},
  {isoTwo: "TG", code: "228", name: "Togo", format: "## ### ###"},
  {isoTwo: "TK", code: "690", name: "Tokelau", format: "## ####"},
  {isoTwo: "TO", code: "676", name: "Tonga", format: "##-#####"},
  {isoTwo: "TT", code: "1-868", name: "Trinidad and Tobago", format: "###-####"},
  {isoTwo: "TN", code: "216", name: "Tunisia", format: "## ### ###"},
  {isoTwo: "TR", code: "90", name: "Turkey", format: "### ### ####"},
  {isoTwo: "TM", code: "993", name: "Turkmenistan", format: "## ## ####"},
  {isoTwo: "TC", code: "1-649", name: "Turks and Caicos Islands", format: "###-####"},
  {isoTwo: "TV", code: "688", name: "Tuvalu", format: "## ####"},
  {isoTwo: "VI", code: "1-340", name: "U.S. Virgin Islands", format: "###-####"},
  {isoTwo: "UG", code: "256", name: "Uganda", format: "### ### ###"},
  {isoTwo: "UA", code: "380", name: "Ukraine", format: "## ### ## ##"},
  {isoTwo: "AE", code: "971", name: "United Arab Emirates", format: "### ### ####"},
  {isoTwo: "GB", code: "44", name: "United Kingdom", format: "## #### ####"},
  {isoTwo: "US", code: "1", name: "United States", format: "###-###-####"},
  {isoTwo: "UY", code: "598", name: "Uruguay", format: "### ####"},
  {isoTwo: "UZ", code: "998", name: "Uzbekistan", format: "## ### ## ##"},
  {isoTwo: "VU", code: "678", name: "Vanuatu", format: "#####"},
  {isoTwo: "VA", code: "379", name: "Vatican", format: "## ####"},
  {isoTwo: "VE", code: "58", name: "Venezuela", format: "###-#######"},
  {isoTwo: "VN", code: "84", name: "Vietnam", format: "### #### ###"},
  {isoTwo: "WF", code: "681", name: "Wallis and Futuna", format: "## ## ##"},
  {isoTwo: "EH", code: "212", name: "Western Sahara", format: "## ## ## ##"},
  {isoTwo: "YE", code: "967", name: "Yemen", format: "### ### ###"},
  {isoTwo: "ZM", code: "260", name: "Zambia", format: "### ### ####"},
  {isoTwo: "ZW", code: "26", name: "Zimbabwe", format: "## ### ####"},
];